# Generated by Django 4.1.7 on 2023-04-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custormer",
            old_name="given_name",
            new_name="first_name",
        ),
    ]
