# Generated by Django 4.1.7 on 2023-04-13 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_given_name_to_first_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custormer",
            old_name="first_name",
            new_name="given_name",
        ),
    ]
