# Generated by Django 4.2 on 2023-04-15 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_rename_given_name_custormer_first_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Custormer",
            new_name="Customer",
        ),
    ]
