# Generated by Django 4.2 on 2023-04-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_custormer_customer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrederItem",
            new_name="OrderItem",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="unite_price",
            new_name="unit_price",
        ),
    ]
