# Generated by Django 4.2 on 2023-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_orederitem_orderitem_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="address",
            new_name="customer",
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="carted_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="placed_by",
            new_name="customer",
        ),
        migrations.AlterField(
            model_name="customer",
            name="membership",
            field=models.CharField(
                choices=[("B", "Bronze"), ("S", "Silver"), ("G", "Gold")],
                default="B",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=1,
            ),
        ),
    ]
